baseURL = "https://shonyuyang.github.io/pidea/"
languageCode = "zh-tw"
title = "Pidea - Pi Projects"
theme = "congo"

[params]
  # Congo 特定設定
  colorScheme = "blowfish" # 預設深色主題
  defaultAppearance = "dark"
  
  [params.author]
    name = "Shonyu"
    image = "img/author.jpg" # 之後可以放頭像
    headline = "Raspberry Pi & AI Enthusiast"
    bio = "探索低功耗運算的無限可能。"
    links = [
      { email = "mailto:your-email@example.com" },
      { github = "https://github.com/ShonyuYang" }
    ]

[markup.goldmark.renderer]
  unsafe = true # 允許在 markdown 中使用 HTML

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "標籤"
    url = "/tags/"
    weight = 20
